### ISSUE TITLE
android 支付完后 不是应该promise.resolve(result)吗

### ISSUE THREAD

**Issue by 420303865** [huangzuizui/rn-alipay#2]
https://github.com/huangzuizui/rn-alipay/blob/master/android/src/main/java/com/RNAlipay/RNAlipayModule.java
104 行 支付完成后 不是应该 promise.resolve(result ); 吗
为什么是 promise.resolve(payInfo); 呢

希望能像https://github.com/myoula/react-native-payment-alipay/blob/master/android/src/main/java/com/payment/alipay/AlipayModule.java 这个里面的支付一样 能对支付结果先做个处理 然后再promise.resolve 给js用。请原谅 我不会java 也不会objectc

**Comment by huangzuizui** [comment]
感谢你的建议，已经修改
